datasets:
  - ./pyrit/datasets/seed_prompts/illegal.prompt
scenarios:
  - type: "RedTeamingAttack"

objective_target:
  type: "HuggingFaceEndpointTarget"
  model_name: "gpt2"

attack_adversarial_config:
  type: "HuggingFaceEndpointTarget"
  model_name: "gpt2"

scoring:
  objective_scorer:
    type: "SelfAskTrueFalseScorer"
    true_false_question_path: pyrit/score/config/true_false_question/task_achieved.yaml

database:
  type: "SQLite"
  memory_labels:
    operator: localuser
    operation: huggingface_test

execution_settings:
  type: local
